<?php
// module/Album/view/album/album/index.phtml:

$title = 'Deployments';
$this->headTitle($title);
?>
<h1>&nbsp;</h1>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Build id</th>
        <th>path</th>
        <th>Date</th>
    </tr>
    <?php foreach ($deployments as $deployment) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($deployment->getId());?></td>
            <td><?php echo $this->escapeHtml($deployment->getPath());?></td>
            <td><?php echo $this->escapeHtml($deployment->getDate()->format('Y/m/d h:i:s'));?></td>
        </tr>
    <?php endforeach; ?>
</table>