
<h1>&nbsp;</h1>
<h1>Login</h1>

<form class="navbar-form navbar-left" role="search" method="POST">
    <div class="form-group">
        <input type="text" name="username" class="form-control" placeholder="username">
    </div>
    <div class="form-group">
        <input type="password" name="password" class="form-control" placeholder="password">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

<?php if (!empty($this->error)) :?>
    <span><?=$this->error?></span>
<?php endif; ?>