
<h1>&nbsp;</h1>
<h1>Login</h1>

<?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formInput ($form->get('username'));
    echo $this->formInput($form->get('password'));
    echo $this->formButton($form->get('submit'));
    echo $this->form()->closeTag();
?>

<!--<form class="navbar-form navbar-left" role="search" method="POST">-->
<!--    <div class="form-group">-->
<!--        <input type="text" name="username" class="form-control" placeholder="username">-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <input type="password" name="password" class="form-control" placeholder="password">-->
<!--    </div>-->
<!--    <button type="submit" class="btn btn-default">Submit</button>-->
<!--</form>-->

<?php if (!empty($this->error)) :?>
    <span><?=$this->error?></span>
<?php endif; ?>