<?php
// module/Album/view/album/album/index.phtml:

$title = 'Deployments';
$this->headTitle($title);
?>
<h1>&nbsp;</h1>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Build id</th>
        <th>path</th>
        <th>Date</th>
    </tr>
    <?php foreach ($deployments as $deployment) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($deployment->buildId);?></td>
            <td><?php echo $this->escapeHtml($deployment->path);?></td>
            <td><?php echo $this->escapeHtml(date('d/m/Y H:i:s', $deployment->date));?></td>
        </tr>
    <?php endforeach; ?>
</table>