<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Continuous Deploy Agent');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headLink(array('rel' => 'icon', 'type' => '/image/vnd.microsoft.icon', 'href' => $this->basePath('/favicon.ico')));
    ?>
</head>
<body>
<div class="container">
    <?php echo $this->content; ?>
</div>
<footer>
    <hr>
    <div class="container center-block">
        <div class="row">
            <div class="col-sm-6">
                <p class="pull-left">&copy; Copyright 2016 - <?php echo date('Y') ?> by <a href="http://continuous.lu">Continuous</a> S.A.</p></div>
            <div class="col-sm-6"><p class="pull-right">For more information <a href="https://continuousphp.com">continuousphp.com</a></p></div>
        </div>
    </div>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
